replicaCount: 2
image: qlikea/engine
imageTag: 12.59.0
service:
  name: qix
  externalPort: 9076
  internalPort: 9076
  promName: prometheus
  prometheusPort: 9090
global:
  serviceType: NodePort
  restartPolicy: Never